export const bankCategories = [
  { code: "401", name: "ASO Savings and & Loans" },
  { code: "044", name: "Access Bank" },
  { code: "323", name: "Access Money" },
  { code: "317", name: "Cellulant" },
  { code: "303", name: "ChamsMobile" },
  { code: "023", name: "CitiBank" },
  { code: "559", name: "Coronation Merchant Bank" },
  { code: "551", name: "Covenant Microfinance Bank" },
  { code: "063", name: "Diamond Bank" },
  { code: "302", name: "Eartholeum" },
  { code: "307", name: "EcoMobile" },
  { code: "050", name: "Ecobank Plc" },
  { code: "084", name: "Enterprise Bank" },
  { code: "309", name: "FBNMobile" },
  { code: "314", name: "FET" },
  { code: "601", name: "FSDH" },
  { code: "070", name: "Fidelity Bank" },
  { code: "318", name: "Fidelity Mobile" },
  { code: "011", name: "First Bank of Nigeria" },
  { code: "214", name: "First City Monument Bank" },
  { code: "501", name: "Fortis Microfinance Bank" },
  { code: "308", name: "FortisMobile" },
  { code: "058", name: "GTBank Plc" },
  { code: "315", name: "GTMobile" },
  { code: "324", name: "Hedonmark" },
  { code: "030", name: "Heritage" },
  { code: "415", name: "Imperial Homes Mortgage Bank" },
  { code: "301", name: "JAIZ Bank" },
  { code: "402", name: "Jubilee Life Mortgage Bank" },
  { code: "082", name: "Keystone Bank" },
  { code: "313", name: "Mkudi" },
  { code: "325", name: "MoneyBox" },
  { code: "999", name: "NIP Virtual Bank" },
  { code: "552", name: "NPF MicroFinance Bank" },
  { code: "990", name: "Omoluabi Mortgage Bank" },
  { code: "327", name: "Pagatech" },
  { code: "560", name: "Page MFBank" },
  { code: "526", name: "Parralex" },
  { code: "329", name: "PayAttitude Online" },
  { code: "305", name: "Paycom" },
  { code: "311", name: "ReadyCash (Parkway)" },
  { code: "403", name: "SafeTrust Mortgage Bank" },
  { code: "076", name: "Skye Bank" },
  { code: "221", name: "Stanbic IBTC Bank" },
  { code: "304", name: "Stanbic Mobile Money" },
  { code: "068", name: "Standard Chartered Bank" },
  { code: "232", name: "Sterling Bank" },
  { code: "326", name: "Sterling Mobile" },
  { code: "100", name: "SunTrust Bank" },
  { code: "90115", name: "TCF MFB" },
  { code: "328", name: "TagPay" },
  { code: "319", name: "TeasyMobile" },
  { code: "523", name: "Trustbond" },
  { code: "032", name: "Union Bank" },
  { code: "033", name: "United Bank for Africa" },
  { code: "215", name: "Unity Bank" },
  { code: "320", name: "VTNetworks" },
  { code: "035", name: "Wema Bank" },
  { code: "057", name: "Zenith Bank" },
  { code: "322", name: "ZenithMobile" },
  { code: "306", name: "eTranzact" },
];